#!/bin/bash

curl -H 'content-type: application/json' -d "{\"email\":\"dathan@udacity.com\",\"password\":\"$(pass show udacity/dathan@udacity.com | sed -e 's/"/\\"/g')\"}" https://user-api.udacity.com/signin | jq -r .jwt
