#!/usr/bin/env python3

import sys
import json

data = sys.stdin.read().strip()

decoder = json.JSONDecoder()

original_task, offset = decoder.raw_decode(data)
modified_task, offset = decoder.raw_decode(data[offset:].strip())

deleted=False

print(json.dumps(modified_task))

if 'jira' not in modified_task:
    sys.exit(0)

jira = modified_task['jira']

if modified_task['status'] == 'deleted':
    print("Task is linked to jira https://jira.netflix.net/browse/{ticket} . If you delete the task, you'll no longer be tracking the ticket locally.".format(ticket=jira))
    sys.exit(0)

if modified_task['status'] == 'completed':
    print("Task is linked to jira https://jira.netflix.net/browse/{ticket} . Consider closing it, too.".format(ticket=jira))
    sys.exit(0)

sys.exit(0)

